name: Final

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y git build-essential flex bison libssl-dev bc gcc-aarch64-linux-gnu
      - run: git clone --depth=1 --branch common-android15-6.6 https://android.googlesource.com/kernel/common.git kernel
      - run: cd code && make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- -C ../kernel M=$PWD modules
      - uses: actions/upload-artifact@v4
        with:
          name: dream.ko
          path: code/dream.ko
